plugins {
    id 'com.android.application'
}

android {
    //noinspection GradleDependency
    compileSdk 35
    namespace "mt.modder.hub.axml"

    defaultConfig {
        applicationId "mt.modder.hub.axml"
        minSdk 21
        //noinspection ExpiredTargetSdkVersion
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {

    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':library')
    implementation files('libs/arsc.jar')
    implementation files('libs/guava.jar')
}
